org: certino
app: certino
service: fxservice

plugins:
  - serverless-domain-manager
  - serverless-plugin-datadog
  - serverless-python-requirements
  - serverless-wsgi

custom:
  customDomain:
    domainName: certino-svs.net
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  wsgi:
    app: fxservice.app
  pythonRequirements:
    pythonBin: python3
  datadog:
    site: "datadoghq.eu"
    addLayers: true
    apiKey: "28cacd85b9b0ba76c07e510e8e7c6166"
    flushMetricsToLogs: false

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  shouldStartNameWithService: true

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'