service: fxservice

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: fxservice.app
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  shouldStartNameWithService: true

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'