service: fxservice

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: fxservice.app

provider:
  name: aws
  runtime: python3
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'